org.gradle.jvmargs=-Xmx1024m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
backendBaseUrl=http://10.0.2.2:3000/api/v1/
org.gradle.daemon=false
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
systemProp.kotlin.compiler.execution.strategy=in-process
systemProp.kotlin.incremental=false
